# Generated by Django 3.2.9 on 2022-05-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalpiteArquivo',
            fields=[
                ('id_parq', models.AutoField(primary_key=True, serialize=False)),
                ('palp_file', models.FileField(upload_to='')),
                ('parq_dt_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id_palp', models.AutoField(primary_key=True, serialize=False)),
                ('palp_dt_criacao', models.DateTimeField(auto_now=True)),
                ('palp_dezenas', models.CharField(max_length=100)),
                ('palp_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.palpitearquivo')),
            ],
        ),
    ]
