# Generated by Django 3.2.9 on 2022-05-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpitearquivo',
            name='palp_file_nome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
