# Generated by Django 3.2.9 on 2022-05-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_palpitearquivo_palp_file_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palpitearquivo',
            name='palp_file',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
    ]
